"""Atomic file output: validated JSON, readable Markdown, the run manifest and the CSV report."""

from __future__ import annotations

import csv
import io
import json
import os
import secrets
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from pydantic import BaseModel

from .schemas import CaseExtraction, CaseSummary, CustomerEmail

RUN_SUBDIRS = ("structured_data", "customer_emails", "case_summaries")

REPORT_FIELDS = [
    "run_id", "document_id", "source_file", "file_format", "provider_mode",
    "processing_status", "extraction_status", "email_status", "summary_status",
    "customer_name", "email", "phone_number", "product_or_service", "complaint_category",
    "complaint", "escalation_required", "supporting_document_available", "overall_case_status",
    "review_required", "recipient_missing", "missing_information", "ambiguities",
    "structured_output_path", "email_output_path", "summary_output_path", "email_skip_reason",
    "error_stage", "error_code", "error_message", "duration_seconds",
]

# Cells starting with these are interpreted as formulas by spreadsheet apps.
FORMULA_PREFIXES = ("=", "+", "-", "@", "\t", "\r")


def make_run_id(now: datetime | None = None) -> str:
    now = now or datetime.now(timezone.utc)
    return f"{now.strftime('%Y%m%dT%H%M%SZ')}-{secrets.token_hex(2)}"


def create_run_dir(output_root: Path, run_id: str) -> Path:
    """Each run gets its own folder; an existing folder is never reused or overwritten."""
    run_dir = output_root / run_id
    run_dir.mkdir(parents=True, exist_ok=False)
    for sub in RUN_SUBDIRS:
        (run_dir / sub).mkdir()
    return run_dir


def atomic_write_text(path: Path, text: str, encoding: str = "utf-8") -> None:
    """Write to a temp file in the same folder, fsync, then rename over the target, so a
    crash or Ctrl+C never leaves a half-written output file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding=encoding, newline="") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def write_model_json(path: Path, model: BaseModel) -> None:
    atomic_write_text(path, model.model_dump_json(indent=2) + "\n")


def write_json(path: Path, data: Any) -> None:
    atomic_write_text(path, json.dumps(data, indent=2, ensure_ascii=False, default=str) + "\n")


def render_email_markdown(email: CustomerEmail, extraction: CaseExtraction, source_file: str,
                          provider_label: str) -> str:
    recipient = extraction.email or "RECIPIENT MISSING - no email address in the source document"
    full_body = f"{email.greeting}\n\n{email.body}\n\n{email.closing}"
    return (
        f"# Customer email draft - {source_file}\n\n"
        f"> **DRAFT ONLY - NOT SENT.** Review before sending. Generated by: {provider_label}.\n\n"
        f"**To:** {recipient}\n\n"
        f"**Subject** (copy):\n\n```text\n{email.subject}\n```\n\n"
        f"**Email body** (copy):\n\n```text\n{full_body}\n```\n"
    )


def render_summary_markdown(summary: CaseSummary, source_file: str, provider_label: str) -> str:
    review = "YES" if summary.review_required else "No"
    reasons = "".join(f"- {r}\n" for r in summary.review_reasons) or "- None\n"
    return (
        f"# Internal case summary - {source_file}\n\n"
        f"> Internal use only. Generated by: {provider_label}.\n\n"
        f"| | |\n|---|---|\n"
        f"| **Case overview** | {_md_cell(summary.case_overview)} |\n"
        f"| **Key issue** | {_md_cell(summary.key_issue)} |\n"
        f"| **Action taken (documented)** | {_md_cell(summary.action_taken)} |\n"
        f"| **Current status** | {_md_cell(summary.current_status)} |\n"
        f"| **Recommended next action (proposal)** | {_md_cell(summary.recommended_next_action)} |\n"
        f"| **Review required** | {review} |\n\n"
        f"## Review reasons\n\n{reasons}"
    )


def _md_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", "<br>")


def escape_csv_cell(value: Any) -> str:
    """Stringify and neutralise spreadsheet formulas by prefixing a single quote.
    Canonical values are kept unchanged in the JSON outputs."""
    if value is None:
        return ""
    text = str(value)
    if text.startswith(FORMULA_PREFIXES):
        return "'" + text
    return text


def render_report_csv(rows: Iterable[dict[str, Any]]) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=REPORT_FIELDS, extrasaction="raise", lineterminator="\r\n")
    writer.writeheader()
    for row in rows:
        writer.writerow({k: escape_csv_cell(row.get(k)) for k in REPORT_FIELDS})
    return buf.getvalue()


def write_report_csv(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    # utf-8-sig adds a BOM so Excel detects UTF-8; other tools ignore it.
    atomic_write_text(path, render_report_csv(rows), encoding="utf-8-sig")
